Repository Anupkjha2601/foodie-blog, pull requests merged in 2023-12, with the labels that each got.

#14 Update about.html
  about.html
Labels: CodePeak'23, easy

#17 Font color of subscribe input changed
  assets/css/style-starter.css
Labels: CodePeak'23, easy

#24 Update contact.html
  contact.html
Labels: 1-POINT

#26 Fixes Issue #13: Optimized plugin for faster animation and readability improvements
  README.md
  assets/js/counter.js
Labels: CodePeak'23, HARD

#25 added left and right nav functionality
  assets/css/style-starter.css
  index.html
Labels: CodePeak'23, MEDIUM

#28 Added Hover Effects On Social Media Icons
  assets/css/style-starter.css
  index.html
Labels: CodePeak'23, MEDIUM

#35 Fixes Issue #29: Fixed Bug in Contact Page
  about.html
  contact.html
  index.html
Labels: CodePeak'23, MEDIUM

#34 Create CONTRIBUTION.md #1
  CONTRIBUTION.md
Labels: CodePeak'23, HARD

#37 Resolved merge conflict in index.html
  Feedback.html
  about.html
  assets/css/style-starter.css
  contact.html
  index.html
Labels: CodePeak'23, HARD

#41 Update counter.js
  assets/js/counter.js
Labels: CodePeak'23, HARD

#42 Update theme-change.js
  assets/js/theme-change.js
Labels: CodePeak'23, HARD

#43 Fixes Issue #38: Added Favicon and optimized code for better readability of all pages.
  about.html
  assets/images/favicon.png
  contact.html
  index.html
  login.html
  signup.html
Labels: CodePeak'23, HARD

#36 fixed navbar issue
  assets/css/style-starter.css
  index.html
Labels: CodePeak'23, HARD

#46 Update about.html
  about.html
Labels: CodePeak'23, MEDIUM

#47 Update Feedback.html
  Feedback.html
Labels: CodePeak'23, MEDIUM

#54 Update style-starter.css #40
  assets/css/style-starter.css
Labels: CodePeak'23, HARD

#50 Fixes Issue #49: Updated Log in and Sign-Up pages for better UI and also Optimized code for various sections.
  login-page.js
  login.css
  login.html
  login.js
  signup.css
  signup.html
  signup.js
  style.css
  styles.css
Labels: CodePeak'23, HARD

#56 Update login-page.js
  login-page.js
Labels: CodePeak'23, HARD

#59 fixed navbar dark-mode bug #58
  assets/css/style-starter.css
Labels: CodePeak'23, HARD

#57 feat: Added Space Between Moon Icon And Search Icon #44
  about.html
  assets/css/style-starter.css
  index.html
Labels: CodePeak'23, HARD

#62 Fixes Issue #49: Refactor UI on Log in and Sign-Up Pages, Optimize Code, and Enhance Documentation
  CONTRIBUTION.md
  Feedback.html
  README.md
  login-page.js
  login.css
  login.html
  login.js
  signup.css
  signup.html
  signup.js
  style.css
  styles.css
Labels: CodePeak'23, BONUS

#63 Overall UI of website #61
  assets/css/style-starter.css
  index.html
Labels: CodePeak'23, BONUS

#64 Improved Feature: Solves issue #9, updated README with clearer instructions and information.
  README.md
Labels: CodePeak'23, BONUS
